### ISSUE TITLE
博主您好，我有一个疑惑，请问为什么代码的输入文件还需要Groundtruth.txt呢？不是应该预测输出吗，麻烦您了

### ISSUE THREAD

**Issue by zchoi** [cwhgn/EGTracker#3]
博主您好，我有一个疑惑，请问为什么代码的输入文件还需要Groundtruth.txt呢？不是应该预测输出吗，麻烦您了

**Comment by cwhgn** [comment]
Groundtruth.txt是提供的检测的groundtruth，不是跟踪的。
